### ISSUE TITLE
change user config directory to .sdss

### ISSUE THREAD

**Issue by havok2063** [sdss/sdsstools#1]
Could, or should, we change the default user config directory from `.config` to `.sdss`?  This would still consolidate all `sdss` package configs under one umbrella but make it distinct by name from non-sdss package configs.

**Comment by joelbrownstein** [comment]
Yes, that sounds like a good generalization

**Comment by albireox** [comment]
In general I'm ok with that. We have been a bit all over the place. Should we do `~/.config/sdss` instead? I think the current standard is to use `~/.config` for all configuration files.

**Comment by havok2063** [comment]
Yeah we've been a bit inconsistent.  I'm ok with `~/.config/sdss/` if `.config` is the current standard.   A related issue is about naming conventions which I've put in a separate issue #2.
