### ISSUE TITLE
Add include config file yaml constructor

### ISSUE THREAD

**Issue by wasndas** [sdss/sdsstools#29]
Some config files will grow quite big, splitting the config files whould be quite good to have,
could you add an include contructor like that to[ sdsstools.configuration.read_yaml_file()](
https://github.com/sdss/sdsstools/blob/bf6bc150bac91a4638b22860cf0f85408ab39ce2/src/sdsstools/configuration.py#L58)

As an alternative, could you add a named argument in [clu.base.from_config()](https://github.com/sdss/clu/blob/634d9f20895f8e5e2b8d3ba27e125ece2227af7c/python/clu/base.py#L147) for a  yaml.loader passing to sdsstools.configuration.read_yaml_file() internally.

So far I am using something like this:

https://github.com/wasndas/lvmnps/blob/master/python/lvmnps/etc/lvmnps/

```
from yaml import SafeLoader, load
from sdsstools import read_yaml_file

class Loader(SafeLoader):
    def __init__(self, stream):
        self._root = os.path.split(stream.name)[0]
        super(Loader, self).__init__(stream)
        self.add_constructor('!include', Loader.include)
    def include(self, node):
        filename = os.path.join(self._root, self.construct_scalar(node))
        with open(filename, 'r') as f:
            return load(f, Loader)

lvmnps_obj = NpsActorInstance.from_config(read_yaml_file(config_file, loader=Loader))
```

- Its not the best solution, because it only overrides and does not merge parameters.
- The path of the included configs are the same as the master one.

**Comment by albireox** [comment]
Allowing to pass a loader to `from_config()` is now implemented in CLU's main.
